### ISSUE TITLE
CSS broken

### ISSUE THREAD

**Issue by adamchainz** [fgimian/fgimian.github.io#2]
github.io is HTTPS only now (at least for me with HTTPS Everywhere browser extension), so the CSS doesn't load because the code is hardcoded to HTTP urls:

![screen shot 2017-12-08 at 14 46 08](https://user-images.githubusercontent.com/857609/33770717-9f7554d2-dc26-11e7-98d4-b39f55ad4035.png)

I managed to read the useful post on Python mocks (thanks!) but it would be best if the CSS were fixed!

**Comment by fgimian** [comment]
Thanks for the tip, I'll try to sort this out.  However HTTP works ok here 😄

**Comment by adamchainz** [comment]
I made a PR, #3 , that should do it. As I said I think it's the HTTPS Everywhere browser extension.
