### ISSUE TITLE
Late-breaking news: windows-rs now has an `h!` macro

### ISSUE THREAD

**Issue by tim-weis** [fgimian/fgimian.github.io#4]
I just finished reading [Working With Strings in windows-rs](https://fgimian.github.io/blog/2022/10/23/working-with-strings-in-windows-rs/), and while I don't exactly match the target audience demographic, I'm sure that Rust developers new to Windows programming will find an all-around valuable blog post: It's well-paced, covers pretty much every relevant use case, and is structured in a way that facilitates building up a useful mental model.

All due praises aside, the release of [version 0.43.0](https://crates.io/crates/windows/0.43.0) of windows-rs [introduced](https://github.com/microsoft/windows-rs/blob/master/crates/libs/windows/src/core/strings/literals.rs#L38-L60) the `h!` macro, which is equivalent to the `w!` macro in versions prior to 0.43. The new `w!` macro ultimately just produces a `*const u16` without the overhead of the `HSTRING_HEADER`, leaving the `HSTRING`-iness to the `h!` macro. That's a welcome change, at the expense of rendering part of your blog entry (introducing the `w!` macro) invalid.

I'm not sure how to reword that paragraph, or expand on it, or how to manage version-dependent information in general, for that matter. Though, if you feel like updating the blog entry I'd offer to provide feedback on those changes, if desired.

**Comment by fgimian** [comment]
Thanks heaps for the comments.  I noticed the update to the macros recently too and will update the post to reflect them this weekend. 😄 

Cheers
Fotis
